version: "3.9"

services:
  central_dashboard:
    image: golang:alpine
    container_name: bcbsks_central_dashboard
    volumes:
      - ./central-dashboard:/infra
    working_dir: /infra
    # entrypoint: sh -c "go mod init example.com/m"
    # entrypoint: sh -c "go mod tidy"
    entrypoint: ["go", "run", "main.go"]
    ports:
      - 8080:8080
    env_file:
      - ./central-dashboard/.env
  broker:
    image: golang:alpine
    container_name: bcbsks_broker-app
    volumes:
      - ./broker-app:/infra
    working_dir: /infra
    # entrypoint: sh -c "go mod init example.com/m"
    # entrypoint: sh -c "go mod tidy"
    entrypoint: ["go", "run", "main.go"]
    ports:
      - "8081:8080"
    env_file:
      - ./broker-app/.env
  employer:
    image: golang:alpine
    container_name: bcbsks_employer-app
    volumes:
      - ./employer-app:/infra
    working_dir: /infra
    # entrypoint: sh -c "go mod init example.com/m"
    # entrypoint: sh -c "go mod tidy"
    entrypoint: ["go", "run", "main.go"]
    ports:
      - "8082:8080"
    env_file:
      - ./employer-app/.env
